### ISSUE TITLE
Footer Navigation to step through necessary Care Plan steps

### ISSUE THREAD

**Issue by awatson1978** [DxRx/dxrx-aud#111]

**Comment by awatson1978** [comment]
browHistory.push('/go/to/route')

**Comment by awatson1978** [comment]
Just as an FYI, I updated the Footer component, and moved the theming controls out of the way.  They can now be toggled with `ctrl-cmd-t`, but otherwise, the footer is now cleared up for navigation controls.

https://github.com/DxRx/dxrx-aud/blob/master/webapp/imports/ui/components/Footer.jsx

**Comment by robertnix** [comment]
Doing the card workflow instead of this idea.
