### ISSUE TITLE
Drive Card Medication workflows with real per-patient data

### ISSUE THREAD

**Issue by awatson1978** [DxRx/dxrx-aud#119]
Check the CarePlan.actions array

**Comment by robertnix** [comment]
The initial implementation of this is the card workflow, although the server-side data that drives this is not properly hooked up yet.  When we have
1) server-side assignment of medications to patients
2) information about whether the meds should be taken 1x, 2x, or 3x per day
3) information about whether meds have already been taken 0x, 1x, 2x or 3x that day for this patient

Then the place to use this information to drive the card workflow is currently in workflows/questions/SessionStart.js card that sets up the per-session state that drives the card workflow.  (It's currently driving that state with some mocked data, but it should be driving the state from the CarePlan and derived information about per patient meds and medication schedules).

**Comment by awatson1978** [comment]
This issue was moved to DxRx/com.dxrxmedical.treatalcohol#22
