### ISSUE TITLE
Create Naltrexone medication record

### ISSUE THREAD

**Issue by awatson1978** [DxRx/dxrx-aud#129]
https://en.wikipedia.org/wiki/Naltrexone  
https://www.drugs.com/pro/naltrexone.html  
http://www.samhsa.gov/medication-assisted-treatment/treatment/naltrexone

**Comment by awatson1978** [comment]
Do you know if John prescribes Revia, Vivitrol, or generic?

**Comment by awatson1978** [comment]
```
```

**Comment by robertnix** [comment]
The generic.  The other two are 30-day injections that cost $1000/month.

The only information we will have about drugs in the app will be the generic names like "Naltrexone" and their frequency of use per day.   That's it.

 We will not have all of the complex information about dosing and packaging.  We will not have the directions for use.    

We must not spend so much time on stuff that we will not use.
