### ISSUE TITLE
Get list of medications and convert to JSON

### ISSUE THREAD

**Issue by awatson1978** [DxRx/dxrx-aud#130]

**Comment by robertnix** [comment]
Take your “X” as directed

Naltrexone — 50mg 1x per day, morning.  Side effects are slight nausea for first day or two.

Gabapentin — 900mg 2x per day, morning and evening.  Side effects are low.  Associated with abuse — Gabapentin does not make you high but drug abusers believe that it makes other highs better.

Baclofen — 20mg 3x per day, rising in dose to find the borderline of tolerance.  Drug can be very effective at high dose, but dose must be just below the borderline of toxicity.  3x per day needs to be accommodate in the app.

Topiramate — varying dose 1x per day.  Side effects are relatively high.

Thiamine.  Vitamin to start people off.
