### ISSUE TITLE
Gather device UUIDs

### ISSUE THREAD

**Issue by awatson1978** [DxRx/dxrx-aud#4]
When you get the chance, can you get me the UUIDs of any phones or tablets you want to test on? If you don't see the UUID on the device Summary page, click on the label/text underneath Capacity. It rotates between UUID, Serial Number, ICCID, and various other ids.

![e001b184-387c-11e6-8500-e07e8049e9e4](https://cloud.githubusercontent.com/assets/675910/18229252/b54ac5ee-7237-11e6-918b-e3e4108f4182.png)

**Comment by robertnix** [comment]
My phone: 1bed202e88d59684bfc2d056a679fff9ba6a6171

**Comment by awatson1978** [comment]
Completed.  This is performed automatically with XCode 8?
